const getAdminNotificationTemplate = (message) => {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; line-height: 1.6;">
      <h2 style="color: #4a2e15;">New Contact/Feedback Submission</h2>
      <p>A new submission has been received on the TimberHaul website.</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; width: 150px;">Name</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message.name || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Email</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message.email || 'N/A'}</td>
        </tr>
        ${message.phone ? `
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Phone</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message.phone}</td>
        </tr>
        ` : ''}
        ${message.subject ? `
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Subject</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message.subject}</td>
        </tr>
        ` : ''}
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Message / Feedback</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message.message || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Date & Time</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${new Date(message.createdAt || Date.now()).toLocaleString()}</td>
        </tr>
      </table>
      
      <p style="margin-top: 30px; font-size: 12px; color: #777;">
        This email was automatically generated by the TimberHaul system.
      </p>
    </div>
  `;
};

const getUserThankYouTemplate = (message) => {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; line-height: 1.6;">
      <div style="text-align: center; padding: 20px; background-color: #f8f5f0; border-bottom: 3px solid #8b5e3c;">
        <h1 style="color: #4a2e15; margin: 0;">TimberHaul</h1>
      </div>
      
      <div style="padding: 30px 20px;">
        <h2 style="color: #4a2e15;">Thank You for Contacting Us, ${message.name}!</h2>
        <p>We have successfully received your message. Our team is reviewing it and we will respond to you within <strong>24&ndash;48 business hours</strong>.</p>
        
        <div style="background-color: #f9f9f9; border-left: 4px solid #8b5e3c; padding: 15px; margin: 25px 0;">
          <h4 style="margin-top: 0; color: #4a2e15;">Summary of Your Details:</h4>
          <p><strong>Name:</strong> ${message.name || 'N/A'}</p>
          <p><strong>Email:</strong> ${message.email || 'N/A'}</p>
          ${message.phone ? `<p><strong>Phone:</strong> ${message.phone}</p>` : ''}
          ${message.subject ? `<p><strong>Subject:</strong> ${message.subject}</p>` : ''}
          <p><strong>Message:</strong><br/> ${message.message || 'N/A'}</p>
        </div>
        
        <p>If you have any urgent inquiries, please don't hesitate to reach out to us at <a href="mailto:${process.env.EMAIL_USER || 'info@timberhaul.com'}" style="color: #8b5e3c;">${process.env.EMAIL_USER || 'info@timberhaul.com'}</a>.</p>
        
        <p>Warm regards,<br/><strong>The TimberHaul Team</strong></p>
      </div>
      
      <div style="text-align: center; padding: 20px; background-color: #4a2e15; color: #fff; font-size: 12px;">
        <p style="margin: 0;">&copy; ${new Date().getFullYear()} TimberHaul. All rights reserved.</p>
        <p style="margin: 5px 0 0 0;">Premium Timber and Wood Products</p>
      </div>
    </div>
  `;
};

module.exports = {
  getAdminNotificationTemplate,
  getUserThankYouTemplate
};
